# .cargo/config.toml
[build]
# Deny all warnings at build level + optimize for native CPU
rustflags = ["-D", "warnings", "-C", "target-cpu=native"]

# Ensure release builds are optimized and stripped
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
incremental = false
overflow-checks = false
